CREATE EXTERNAL TABLE IF NOT EXISTS results (tday STRING, tweets STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' STORED AS TEXTFILE LOCATION '${OUTPUT}';

INSERT OVERWRITE TABLE results SELECT substr(tdate, 1, 10) AS tday, count(*) AS tweets FROM tweets WHERE ttext LIKE 'RT%' GROUP BY substr(tdate, 1, 10) ORDER BY tweets DESC;

DROP TABLE IF EXISTS results;
